require:
    - ts-node/register/transpile-only

serve:
    customServerHandler: ./src/index.ts

sources:
    - name: WorkspacesService
      handler:
          graphql:
              endpoint: http://localhost:4001/
    #   transforms:
    #       - typeMerging:
    #         queryFields:
    #             - queryFieldName: workspace
    #               keyField: id

    - name: WorkflowsService
      handler:
          graphql:
              endpoint: http://localhost:4002/
    #   transforms:
    #       - typeMerging:
    #             queryFields:
    #                 - queryFieldName: workflow
    #                   keyField: id

transforms:
    - filterSchema:
          filters:
              - Workspace.!workflowIds

additionalTypeDefs: |
    extend type Workspace {
      workflows: [Workflow!]!
    }

additionalResolvers:
    - ./src/mesh-resolvers.ts
