serve:
    customServerHandler: ./dist/index.js

sources:
    - name: WorkspacesService
      handler:
          graphql:
              endpoint: http://localhost:4001/
    - name: WorkflowsService
      handler:
          graphql:
              endpoint: http://localhost:4002/
